server.port=8081
logging.level.org.springframework=INFO

################### DataSource Configuration ##########################
spring.datasource.url=jdbc:mysql://localhost:3306/prevent_diabetes?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=workbench
spring.datasource.password=workbench
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect

################### Hibernate Configuration ##########################
spring.sql.init.mode = always

#Disable Hibernate automatic schema creation
spring.jpa.hibernate.ddl-auto = none

spring.jpa.show-sql=true

################### SWAGGER ###################
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

server.error.include-message=always
