spring.application.name=note
server.port=8082
spring.data.mongodb.uri=mongodb+srv://user:1234@cluster0.cxm0vnb.mongodb.net/prevent_diabetes.note
server.error.include-message=always

################### SWAGGER ##########################
spring.mvc.pathmatch.matching-strategy=ant_path_matcher